version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: fastagency_postgres
    environment:
      POSTGRES_DB: fastagency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastagency_network

  # FastAgency 应用
  fastagency:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastagency_app
    environment:
      # 数据库配置
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fastagency
      
      # OpenAI 配置（需要在 .env 文件中设置或通过环境变量传入）
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE:-0.8}
      
      # 应用配置
      PORT: 8000
      ENABLE_WEB_UI: ${ENABLE_WEB_UI:-false}
      DB_ECHO: ${DB_ECHO:-false}
      
      # 开发环境配置
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # 开发时可以挂载代码目录进行热重载
      - .:/app
    networks:
      - fastagency_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (可选，用于缓存和会话存储)
  redis:
    image: redis:7-alpine
    container_name: fastagency_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastagency_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (可选，用于数据库管理)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastagency_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fastagency.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fastagency_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  fastagency_network:
    driver: bridge